[project]
authors = ["keanesc <145848994+keanesc@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "parkinsons_disease_detection"
platforms = ["linux-64"]
version = "0.1.0"
description = "MRI-based Parkinson's disease classification"

[tasks]

[dependencies]
python = ">=3.9,<3.12"
numpy = ">=2.2.3,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.1,<4"
seaborn = ">=0.13.2,<0.14"
jupyterlab = ">=4.3.5,<5"
flask = ">=3.1.0,<4"
ipywidgets = ">=8.1.5,<9"
transformers = ">=4.49.0,<5"
scikit-learn = ">=1.6.1,<2"

[pypi-dependencies]
pip = ">=25.0.1, <26"
ipykernel = ">=6.29.5, <7"
torch = { version = ">=2.6.0", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.21.0", index = "https://download.pytorch.org/whl/cpu" }
opencv-python = ">=4.11.0.86, <5"
